
# Site settings

url: "https://qhexacoda.github.io/qhexacoda.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

google-tracking-id: "UA-69774437-1"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Weerayoot Ngandee"
lang: "en"
title: "{ Weerayoot Ngandee }"
favicon: "/img/favicon.ico"
description: "Blog and website of Weerayoot Ngandee, blogging mainly for tech. Opinions expressed are mine."
keywords: "Ngandee, Weerayoot, qhexacoda, QWeerayoot, personal, jekyll, iOS Developer, Android Developer, Mobile Developer"

################
# Intro layout #
################

black-favicon: "/img/favicon.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/me.jpeg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Hello friend..."
  - text: "Hello friend..."
  - text: "Everyday we change the world."
  - text: "But to change the world in a way that means anything that takes more time than most people have."

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "qhexacoda"

###############
# Life Events #
###############

events:
  - image: "/img/career/hexacoda_logo.png" #change it to hexacoda logo
    date: "September 2015 - Today"
    description: "Co-Founder & Lead Development at Hexacoda CO.,LTD."
  - image: "/img/career/digitalnoir_logo.png" #change it to digitalnoir logo
    date: "September 2014 - September 2015"
    description: "Mobile Developer & Lead Developer at Digitalnoir"
  - image: "/img/career/buzzwoo_logo.png" #change it to buzzwoo logo
    date: "August 2011 - August 2014"
    description: "iOS Developer at BUZZWOO! Asia CO.,LTD."
  - image: "/img/career/cmu_logo.png" #change it to cmu logo
    date: "June 2007 - March 2011"
    description: "Studied in Bachelor degree of Computer Science at Chiang Mai University, Thailand"

# First image of the Career timeline
career-img: "/img/me.jpeg"

##################
# Contact layout #
##################

email: "weerayoot@hexacoda.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "youtube"
    url: "https://youtube.com/"
  - title: "github"
    url: "https://github.com/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems: [jekyll-paginate]
